/*
 * This file is generated by jOOQ.
 */
package com.tosin.investire.dao.jooq;


import com.tosin.investire.dao.jooq.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.21"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
