/*
 * This file is generated by jOOQ.
 */
package com.tosin.investire.dao.jooq.tables.records;


import com.tosin.investire.dao.jooq.enums.UserStatus;
import com.tosin.investire.dao.jooq.tables.Users;
import com.tosin.investire.dao.jooq.tables.pojos.User;

import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.21"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record8<UUID, String, String, UserStatus, OffsetDateTime, OffsetDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>users.id</code>.
     */
    public UsersRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>users.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>users.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>users.password</code>.
     */
    public UsersRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>users.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>users.status</code>.
     */
    public UsersRecord setStatus(UserStatus value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>users.status</code>.
     */
    public UserStatus getStatus() {
        return (UserStatus) get(3);
    }

    /**
     * Setter for <code>users.created_at</code>.
     */
    public UsersRecord setCreatedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>users.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>users.updated_at</code>.
     */
    public UsersRecord setUpdatedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>users.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>users.first_name</code>.
     */
    public UsersRecord setFirstName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>users.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>users.last_name</code>.
     */
    public UsersRecord setLastName(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>users.last_name</code>.
     */
    public String getLastName() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, String, UserStatus, OffsetDateTime, OffsetDateTime, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, String, String, UserStatus, OffsetDateTime, OffsetDateTime, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return Users.USERS.PASSWORD;
    }

    @Override
    public Field<UserStatus> field4() {
        return Users.USERS.STATUS;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Users.USERS.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Users.USERS.UPDATED_AT;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.FIRST_NAME;
    }

    @Override
    public Field<String> field8() {
        return Users.USERS.LAST_NAME;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public UserStatus component4() {
        return getStatus();
    }

    @Override
    public OffsetDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public String component7() {
        return getFirstName();
    }

    @Override
    public String component8() {
        return getLastName();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public UserStatus value4() {
        return getStatus();
    }

    @Override
    public OffsetDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public String value7() {
        return getFirstName();
    }

    @Override
    public String value8() {
        return getLastName();
    }

    @Override
    public UsersRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UsersRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UsersRecord value4(UserStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public UsersRecord value5(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UsersRecord value6(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UsersRecord value8(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UsersRecord values(UUID value1, String value2, String value3, UserStatus value4, OffsetDateTime value5, OffsetDateTime value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    @ConstructorProperties({ "id", "email", "password", "status", "createdAt", "updatedAt", "firstName", "lastName" })
    public UsersRecord(UUID id, String email, String password, UserStatus status, OffsetDateTime createdAt, OffsetDateTime updatedAt, String firstName, String lastName) {
        super(Users.USERS);

        setId(id);
        setEmail(email);
        setPassword(password);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setFirstName(firstName);
        setLastName(lastName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(User value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setEmail(value.getEmail());
            setPassword(value.getPassword());
            setStatus(value.getStatus());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            resetChangedOnNotNull();
        }
    }
}
