/*
 * This file is generated by jOOQ.
 */
package com.tosin.investire.dao.jooq.enums;


import com.tosin.investire.dao.jooq.DefaultSchema;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.21"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UserStatus implements EnumType {

    verification_completed("verification_completed"),

    awaiting_verification("awaiting_verification");

    private final String literal;

    private UserStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public String getName() {
        return "user_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static UserStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(UserStatus.class, literal);
    }
}
